version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:password@host:port/dbname?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5433:5433"
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_HOST=host
      - DB_PORT=port
      - DB_NAME=dbname
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: